"""Local learning infrastructure for DeskBot.

This package implements a small neural-network framework, experience
memory, state encoding, world model, action learning, background
continual learning, multimodal encoding, preference learning, and
safety evaluation - all running on-device with no external inference
APIs or pretrained models.
"""

from robot.learning.action_learning import (
    REWARD_NEGATIVE,
    REWARD_NEUTRAL,
    REWARD_POSITIVE,
    ActionLearner,
    ActionLearningEnv,
    ActionSpace,
    ActionValidator,
    DefaultValidator,
    LearningAction,
    Reward,
    RewardFunction,
    deskbot_action_space,
)
from robot.learning.dataset import (
    DatasetSplit,
    DatasetStats,
    TransitionDataset,
    WorldModelBaseline,
    validate_transition,
)
from robot.learning.deterministic_encoder import (
    DEFAULT_HISTORY_LENGTH as DETERMINISTIC_HISTORY_LENGTH,
    DETERMINISTIC_ENCODER_VERSION,
    DeterministicMultimodalEncoder,
    ObservationContext,
    deterministic_encoding_size,
)
from robot.learning.evaluation import (
    EVALUATION_DATASET_VERSION,
    EvaluationDataset,
    EvaluationMetrics,
    EvaluationScenario,
    PromotionRule,
    create_standard_evaluation_dataset,
)
from robot.learning.experience import (
    EpisodicMemory,
    Experience,
    ExperienceStore,
    InMemoryExperienceStore,
    ReplayBuffer,
    SqliteExperienceStore,
    WorkingMemory,
)
from robot.learning.learning_service import (
    CheckpointConfig,
    CheckpointManager,
    LearningSchedule,
    LearningService,
    ResourceLimits,
    TrainingStatus,
)
from robot.learning.multimodal import (
    AUDIO_ENCODER_INPUT,
    AUDIO_ENCODER_OUTPUT,
    DEFAULT_HISTORY_LENGTH,
    MULTIMODAL_BASE_SIZE,
    MULTIMODAL_VERSION,
    VISION_ENCODER_INPUT as VISION_ENCODER_INPUT,
    VISION_ENCODER_OUTPUT as VISION_ENCODER_OUTPUT,
    AudioEncoder,
    HistoryBuffer,
    MultimodalEncoder,
    MultimodalEnvironment,
    VisionEncoder,
    multimodal_size,
)
from robot.learning.network import MLP, Network
from robot.learning.observation import (
    AudioObservation,
    Observation,
    RobotObservation,
    VisionObservation,
    event_to_observation_update,
)
from robot.learning.preference_learner import (
    LearnedPreference,
    PatternObservation,
    PreferenceLearner,
)
from robot.learning.reward import (
    RewardComponent,
    RewardContext,
    RewardModel,
)
from robot.learning.safety import (
    ActionSafetyValidator,
    EvaluationResult,
    EvaluationThresholds,
    LearningSafetyManager,
    ModelEvaluator,
)
from robot.learning.safety_gate import (
    SafeActionExecutor,
    SafetyGate,
    SafetyResult,
    SafetyResultType,
)
from robot.learning.shadow_policy import (
    PolicyMode,
    ShadowLogEntry,
    ShadowMetrics,
    ShadowPolicyController,
)
from robot.learning.state_encoder import (
    ENCODER_VERSION,
    STATE_SIZE,
    AudioFeatures,
    StateEncoder,
    VisionFeatures,
    state_layout,
    state_size,
)
from robot.learning.tensor import Tensor
from robot.learning.transition import (
    PendingTransition,
    Transition,
    TransitionError,
    TransitionStore,
)
from robot.learning.world_model import (
    DEFAULT_ACTION_SIZE,
    SimpleEnvironment,
    TrainingMetrics,
    TrainingResult,
    WorldModel,
)

__all__ = [
    "AUDIO_ENCODER_INPUT",
    "AUDIO_ENCODER_OUTPUT",
    "DEFAULT_ACTION_SIZE",
    "DEFAULT_HISTORY_LENGTH",
    "DETERMINISTIC_ENCODER_VERSION",
    "DETERMINISTIC_HISTORY_LENGTH",
    "ENCODER_VERSION",
    "EVALUATION_DATASET_VERSION",
    "MLP",
    "MULTIMODAL_BASE_SIZE",
    "MULTIMODAL_VERSION",
    "REWARD_NEGATIVE",
    "REWARD_NEUTRAL",
    "REWARD_POSITIVE",
    "STATE_SIZE",
    "ActionLearner",
    "ActionLearningEnv",
    "ActionSafetyValidator",
    "ActionSpace",
    "ActionValidator",
    "AudioEncoder",
    "AudioFeatures",
    "AudioObservation",
    "CheckpointConfig",
    "CheckpointManager",
    "DatasetSplit",
    "DatasetStats",
    "DefaultValidator",
    "DeterministicMultimodalEncoder",
    "EpisodicMemory",
    "EvaluationDataset",
    "EvaluationMetrics",
    "EvaluationResult",
    "EvaluationScenario",
    "EvaluationThresholds",
    "Experience",
    "ExperienceStore",
    "HistoryBuffer",
    "InMemoryExperienceStore",
    "LearnedPreference",
    "LearningAction",
    "LearningSafetyManager",
    "LearningSchedule",
    "LearningService",
    "ModelEvaluator",
    "MultimodalEncoder",
    "MultimodalEnvironment",
    "Network",
    "Observation",
    "ObservationContext",
    "PatternObservation",
    "PendingTransition",
    "PolicyMode",
    "PreferenceLearner",
    "PromotionRule",
    "ReplayBuffer",
    "ResourceLimits",
    "Reward",
    "RewardComponent",
    "RewardContext",
    "RewardFunction",
    "RewardModel",
    "RobotObservation",
    "SafeActionExecutor",
    "SafetyGate",
    "SafetyResult",
    "SafetyResultType",
    "ShadowLogEntry",
    "ShadowMetrics",
    "ShadowPolicyController",
    "SimpleEnvironment",
    "SqliteExperienceStore",
    "StateEncoder",
    "Tensor",
    "TrainingMetrics",
    "TrainingResult",
    "TrainingStatus",
    "Transition",
    "TransitionDataset",
    "TransitionError",
    "TransitionStore",
    "VisionEncoder",
    "VisionFeatures",
    "VisionObservation",
    "WorkingMemory",
    "WorldModel",
    "WorldModelBaseline",
    "create_standard_evaluation_dataset",
    "deskbot_action_space",
    "deterministic_encoding_size",
    "event_to_observation_update",
    "multimodal_size",
    "state_layout",
    "state_size",
    "validate_transition",
]
